term.write("Installing ar-base.lua...")
shell.run("wget https://raw.githubusercontent.com/Mag1cpunch/MeteorOS-AR/main/ar-base.lua")
term.write("Installed")
term.write("Installing startup.lua...")
shell.run("wget https://github.com/Mag1cpunch/MeteorOS-AR/blob/main/startup.lua")
term.write("Installed")
term.write("Rebooting...")
os.sleep(3)
os.reboot()